# .github/workflows/build.yml
name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  linux:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm --needed \
            gtk4 \
            libadwaita \
            gstreamer \
            gst-plugins-base \
            alsa-lib \
            pkgconf \
            rust \
            make \
            base-devel \
            tar

      - name: Cache Cargo
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: linux-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Package
        run: make package-linux

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: meow-simulator-linux
          path: dist/meow-simulator-linux.tar.gz
          compression-level: 0

  windows:
    runs-on: windows-latest
    timeout-minutes: 60
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v6

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          release: true
          install: >-
            mingw-w64-ucrt-x86_64-rust
            mingw-w64-ucrt-x86_64-gtk4
            mingw-w64-ucrt-x86_64-pkgconf
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-vulkan-loader
            mingw-w64-ucrt-x86_64-gstreamer
            mingw-w64-ucrt-x86_64-gst-plugins-base
            mingw-w64-ucrt-x86_64-gst-plugins-good
            mingw-w64-ucrt-x86_64-gst-plugins-bad
            mingw-w64-ucrt-x86_64-libadwaita
            make
            zip
        env:
          MSYS2_PATH_TYPE: inherit

      - name: Cache Cargo
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: windows-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Package
        run: make package-windows

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: meow-simulator-windows
          path: dist/windows/
